### ISSUE TITLE
Error when tried the Search Engine Project 

### ISSUE THREAD

**Issue by ugurlu2001** [ThorstenDoherr/searchengine#2]
Hello Thorsten; 

I download your repo and tried the your vfp project.
When I download and open repo, I got the following error : 

Memo file searchengine.PJT is missing or is invalid.

With my best :)

**Comment by ThorstenDoherr** [comment]
I could replicate the error. Have re-uploaded the searchengine.pjt and .pjx files and the issue seems to be gone. Thanks!
